//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMunicipalArchiveEntities : DbContext
    {
        public dbMunicipalArchiveEntities()
            : base("name=dbMunicipalArchiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAppVersion> tblAppVersion { get; set; }
        public virtual DbSet<tblFile> tblFile { get; set; }
        public virtual DbSet<tblFilePerson> tblFilePerson { get; set; }
        public virtual DbSet<tblFilePlaque> tblFilePlaque { get; set; }
        public virtual DbSet<tblFileType> tblFileType { get; set; }
        public virtual DbSet<tblLicense> tblLicense { get; set; }
        public virtual DbSet<tblPerson> tblPerson { get; set; }
        public virtual DbSet<tblPlaque> tblPlaque { get; set; }
        public virtual DbSet<tblPostType> tblPostType { get; set; }
        public virtual DbSet<tblSecurityAccess> tblSecurityAccess { get; set; }
        public virtual DbSet<tblSecurityQuestion> tblSecurityQuestion { get; set; }
        public virtual DbSet<tblSundry> tblSundry { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblViolation> tblViolation { get; set; }
        public virtual DbSet<viewAll> viewAll { get; set; }
        public virtual DbSet<viewFilePerson> viewFilePerson { get; set; }
        public virtual DbSet<viewFilePlaque> viewFilePlaque { get; set; }
    }
}
