//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewAll
    {
        public Nullable<int> Person_Id { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> MainId { get; set; }
        public Nullable<int> Marlik { get; set; }
        public Nullable<byte> FileType_Id { get; set; }
        public Nullable<byte> Violation_Id { get; set; }
        public Nullable<int> FileNum { get; set; }
        public Nullable<short> FileYear { get; set; }
        public Nullable<int> PermitNum { get; set; }
        public Nullable<short> PermitYear { get; set; }
        public Nullable<int> Mantaghe { get; set; }
        public Nullable<int> Nahie { get; set; }
        public Nullable<int> Mahaleh { get; set; }
        public Nullable<int> Block { get; set; }
        public Nullable<int> Melk { get; set; }
        public Nullable<int> Radif { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string VoteNum { get; set; }
        public Nullable<bool> InArchives { get; set; }
        public Nullable<int> Separation { get; set; }
        public string DateInsert { get; set; }
        public Nullable<int> Aggregation { get; set; }
        public string FileDescription { get; set; }
        public string FullName { get; set; }
        public string FatherName { get; set; }
        public string Code { get; set; }
        public string Birthday { get; set; }
        public Nullable<byte> Sex { get; set; }
        public string Mobile { get; set; }
        public string PersonDescription { get; set; }
        public string FileType { get; set; }
        public string Violation { get; set; }
        public Nullable<int> Plaque_Id { get; set; }
        public string PlaqueDescription { get; set; }
        public string FileNumber { get; set; }
        public string PermitNumber { get; set; }
        public string Reconstruction { get; set; }
        public string PlaqueNum { get; set; }
    }
}
