//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewFilePlaque
    {
        public int File_Id { get; set; }
        public int Id { get; set; }
        public Nullable<int> Main { get; set; }
        public Nullable<int> Secondary { get; set; }
        public Nullable<int> Part { get; set; }
        public string Description { get; set; }
        public int Plaque_Id { get; set; }
    }
}
